import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.185.1/build/three.module.min.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const saveKey='srmono_lavado_total_online_v1';
const saved=JSON.parse(localStorage.getItem(saveKey)||'null')||{money:8750,rep:2350,xp:3450,level:12,upgrades:{foam:0,rinse:0,polish:0}};
let gameState='menu',tool='foam',score=0,timeLeft=150,wanted=0,vehicleDamage=0,using=false,missionMode='wash',last=performance.now(),pointer={x:0,y:0},mobileAim=false;
const keys={w:false,a:false,s:false,d:false}, moveTouch={up:false,down:false,left:false,right:false};
const canvas=$('#game');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x0a0e11);scene.fog=new THREE.FogExp2(0x0b1013,.025);
const camera=new THREE.PerspectiveCamera(55,1,.1,200);camera.position.set(9,6,12);
scene.add(new THREE.HemisphereLight(0xbfd5dc,0x101305,2.2));
const sun=new THREE.DirectionalLight(0xffffff,4);sun.position.set(8,14,7);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);
const lime=0xb6f000, dark=0x090b0d;
const ground=new THREE.Mesh(new THREE.PlaneGeometry(55,55),new THREE.MeshPhysicalMaterial({color:0x171b1c,roughness:.2,metalness:.15,clearcoat:.35}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
for(let i=-12;i<=12;i+=3){const g=new THREE.Mesh(new THREE.BoxGeometry(.07,.025,26),new THREE.MeshStandardMaterial({color:lime,emissive:0x263d00,emissiveIntensity:.5}));g.position.set(i,.02,0);scene.add(g)}
function box(w,h,d,color,x,y,z,matProps={}){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.55,metalness:.15,...matProps}));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);return m}
box(22,.5,.5,dark,0,5,-9);box(22,.5,.5,lime,0,4.65,-9,{emissive:0x263d00,emissiveIntensity:1});box(.5,10,.5,dark,-10.5,2,-9);box(.5,10,.5,dark,10.5,2,-9);
for(const x of [-10.5,-3.5,3.5,10.5]){box(.35,5.2,.35,0x171b1c,x,2.6,-2);box(.35,5.2,.35,0x171b1c,x,2.6,7)}
for(let i=0;i<7;i++){const l=new THREE.PointLight(i%2?0xffffff:lime,25,12,2);l.position.set(-9+i*3,4.5,-1);scene.add(l)}
const logoCanvas=document.createElement('canvas');logoCanvas.width=1024;logoCanvas.height=640;const logoCtx=logoCanvas.getContext('2d');logoCtx.fillStyle='#080a0c';logoCtx.fillRect(0,0,1024,640);logoCtx.strokeStyle='#b6f000';logoCtx.lineWidth=18;logoCtx.beginPath();logoCtx.arc(512,210,125,0,Math.PI*2);logoCtx.stroke();logoCtx.fillStyle='#f5f7f1';logoCtx.font='900 150px Arial';logoCtx.textAlign='center';logoCtx.fillText('MONO',512,260);logoCtx.fillStyle='#f5f7f1';logoCtx.font='900 95px Arial';logoCtx.fillText('Sr. Mono',512,440);logoCtx.fillStyle='#b6f000';logoCtx.font='700 52px Arial';logoCtx.fillText('CAR WASH · MANTA',512,520);const logoTexture=new THREE.CanvasTexture(logoCanvas);logoTexture.colorSpace=THREE.SRGBColorSpace;const sign=new THREE.Mesh(new THREE.PlaneGeometry(7,4.4),new THREE.MeshBasicMaterial({map:logoTexture}));sign.position.set(0,2.5,-8.7);scene.add(sign);
for(let i=0;i<8;i++){box(1+Math.random()*1.2,3+Math.random()*6,1,0x11171a,-18+i*5,1.5,-18-Math.random()*5)}
function makeMonkey(){const g=new THREE.Group();const fur=new THREE.MeshStandardMaterial({color:0x231813,roughness:.92}),black=new THREE.MeshStandardMaterial({color:0x090a0b,roughness:.78}),skin=new THREE.MeshStandardMaterial({color:0x9a684a,roughness:.9});const body=new THREE.Mesh(new THREE.CapsuleGeometry(.55,1.15,7,12),black);body.position.y=1.4;body.castShadow=true;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.55,20,16),fur);head.position.y=2.65;head.castShadow=true;g.add(head);const muzzle=new THREE.Mesh(new THREE.SphereGeometry(.34,16,12),skin);muzzle.scale.set(1,.7,.55);muzzle.position.set(0,2.5,.47);g.add(muzzle);[-.55,.55].forEach(x=>{const e=new THREE.Mesh(new THREE.SphereGeometry(.19,12,10),fur);e.position.set(x,2.65,0);g.add(e)});const cap=new THREE.Mesh(new THREE.SphereGeometry(.57,16,8,0,Math.PI*2,0,Math.PI/2),black);cap.position.y=2.97;g.add(cap);const visor=new THREE.Mesh(new THREE.BoxGeometry(.78,.07,.38),black);visor.position.set(0,2.96,.45);g.add(visor);const glasses=new THREE.Mesh(new THREE.BoxGeometry(.72,.14,.08),new THREE.MeshStandardMaterial({color:0x020202,metalness:.5}));glasses.position.set(0,2.68,.53);g.add(glasses);for(const x of [-.68,.68]){const arm=new THREE.Mesh(new THREE.CapsuleGeometry(.12,.9,5,8),fur);arm.position.set(x,1.52,.08);arm.rotation.z=x<0?-.16:.16;g.add(arm)}for(const x of [-.28,.28]){const leg=new THREE.Mesh(new THREE.CapsuleGeometry(.15,.78,5,8),black);leg.position.set(x,.55,0);g.add(leg);const shoe=new THREE.Mesh(new THREE.BoxGeometry(.4,.2,.62),new THREE.MeshStandardMaterial({color:0x08090a}));shoe.position.set(x,.15,.15);g.add(shoe);const sole=new THREE.Mesh(new THREE.BoxGeometry(.42,.06,.64),new THREE.MeshStandardMaterial({color:lime,emissive:0x203300,emissiveIntensity:.4}));sole.position.set(x,.04,.15);g.add(sole)}const nozzle=new THREE.Mesh(new THREE.BoxGeometry(.12,.12,.75),new THREE.MeshStandardMaterial({color:lime,metalness:.4}));nozzle.name='nozzle';nozzle.position.set(.72,1.55,.62);g.add(nozzle);g.position.set(0,0,7);scene.add(g);return g}
const player=makeMonkey();
const car=new THREE.Group();scene.add(car);const washable=[];
function panel(name,w,h,d,x,y,z,color=0x101317){const base=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshPhysicalMaterial({color,roughness:.42,metalness:.65,clearcoat:1,clearcoatRoughness:.18}));base.position.set(x,y,z);base.castShadow=true;base.receiveShadow=true;base.userData={name,dirt:1,foam:0,wet:0,shine:0,damage:0};car.add(base);washable.push(base);const overlay=new THREE.Mesh(base.geometry.clone(),new THREE.MeshStandardMaterial({color:0xffffff,transparent:true,opacity:0,roughness:1,depthWrite:false}));overlay.position.copy(base.position);overlay.scale.multiplyScalar(1.012);car.add(overlay);base.userData.overlay=overlay;return base}
function buildCar(){while(car.children.length)car.remove(car.children[0]);washable.length=0;panel('Capó',2.2,.45,2.05,1.7,1.25,0);panel('Cabina',1.9,1.15,1.9,.1,1.7,0);panel('Caja',1.45,.65,2,-1.7,1.15,0);panel('Puerta izquierda',1.55,.85,.12,.1,1.25,1.02);panel('Puerta derecha',1.55,.85,.12,.1,1.25,-1.02);panel('Frente',.15,.75,1.9,2.82,1.05,0);panel('Trasera',.15,.75,1.9,-2.55,1.05,0);panel('Techo',1.6,.12,1.82,.1,2.34,0);for(const x of [-1.55,1.55])for(const z of [-1.08,1.08]){const wheel=new THREE.Mesh(new THREE.CylinderGeometry(.5,.5,.36,20),new THREE.MeshStandardMaterial({color:0x050505,roughness:.72}));wheel.rotation.x=Math.PI/2;wheel.position.set(x,.56,z);wheel.castShadow=true;car.add(wheel);const rim=new THREE.Mesh(new THREE.CylinderGeometry(.28,.28,.38,12),new THREE.MeshStandardMaterial({color:0x15191b,metalness:.8,roughness:.25}));rim.rotation.x=Math.PI/2;rim.position.copy(wheel.position);car.add(rim)}car.position.set(0,0,0);car.rotation.y=Math.PI/2}
buildCar();
const raycaster=new THREE.Raycaster();const sprayGeo=new THREE.BufferGeometry();const sprayCount=90;const sprayPositions=new Float32Array(sprayCount*3);sprayGeo.setAttribute('position',new THREE.BufferAttribute(sprayPositions,3));const spray=new THREE.Points(sprayGeo,new THREE.PointsMaterial({color:0xdff8ff,size:.08,transparent:true,opacity:.9}));spray.visible=false;scene.add(spray);
function resize(){const w=innerWidth,h=innerHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
function setTool(t){tool=t;$$('.tool[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));toast(({foam:'Cañón de espuma',rinse:'Hidrolavadora',dry:'Sopladora de secado',polish:'Pulidora'})[t])}
function resetMission(mode='wash'){missionMode=mode;score=0;timeLeft=mode==='free'?9999:150;wanted=0;vehicleDamage=0;buildCar();if(mode==='detail'){washable.forEach(p=>{p.userData.dirt=.18;p.userData.foam=0;p.userData.wet=0;p.userData.shine=.05});setTool('polish');$('#missionName').textContent='La Prueba del Reflejo';$('#objectiveText').textContent='Elimina marcas y logra brillo espejo'}else if(mode==='free'){$('#missionName').textContent='Modo Libre';$('#objectiveText').textContent='Explora el local y practica con las herramientas';setTool('foam')}else{$('#missionName').textContent='Espuma Total';$('#objectiveText').textContent='Lava, enjuaga, seca y pule el vehículo';setTool('foam')}updateHUD()}
function start(mode='wash'){gameState='game';$('#menu').classList.add('hidden');$('#hud').classList.remove('hidden');$('#crosshair').classList.remove('hidden');$('#actionMessage').classList.remove('hidden');$('#mobileControls').classList.remove('hidden');resetMission(mode);last=performance.now()}
function goMenu(){gameState='menu';$('#menu').classList.remove('hidden');$('#hud').classList.add('hidden');$('#crosshair').classList.add('hidden');$('#actionMessage').classList.add('hidden');$('#mobileControls').classList.add('hidden');$('#missionComplete').classList.add('hidden');$('#pauseScreen').classList.add('hidden');using=false;save()}
function save(){localStorage.setItem(saveKey,JSON.stringify(saved))}
function toast(msg,danger=false){const t=$('#toast');t.textContent=msg;t.style.borderColor=danger?'#ff3131':'var(--line)';t.classList.add('show');clearTimeout(t._to);t._to=setTimeout(()=>t.classList.remove('show'),1600)}
function averages(){let dirt=0,foam=0,wet=0,shine=0;washable.forEach(p=>{dirt+=p.userData.dirt;foam+=p.userData.foam;wet+=p.userData.wet;shine+=p.userData.shine});const n=washable.length;return{dirt:dirt/n,foam:foam/n,wet:wet/n,shine:shine/n}}
function progressValue(){const a=averages();return THREE.MathUtils.clamp(((1-a.dirt)*.4+(1-a.foam)*.2+(1-a.wet)*.15+a.shine*.25)*100,0,100)}
function updatePanelVisual(p){const d=p.userData;const overlay=d.overlay;overlay.material.opacity=Math.max(d.foam*.82,d.dirt*.48);overlay.material.color.set(d.foam>.1?0xffffff:0x69452d);p.material.roughness=THREE.MathUtils.lerp(.8,.12,d.shine)*(1-d.wet*.3);p.material.clearcoat=THREE.MathUtils.lerp(.3,1,d.shine);p.material.color.setHex(d.damage>.1?0x2b1010:0x101317)}
function applyTool(p,dt,point){const d=p.userData;const up=saved.upgrades;let changed=false;if(tool==='foam'){d.foam=Math.min(1,d.foam+dt*(.42+up.foam*.12));d.wet=Math.min(1,d.wet+dt*.1);changed=true}else if(tool==='rinse'){const power=.32+up.rinse*.08;d.foam=Math.max(0,d.foam-dt*.5);d.dirt=Math.max(0,d.dirt-dt*power*(d.foam>.02?1.35:.65));d.wet=Math.min(1,d.wet+dt*.35);changed=true}else if(tool==='dry'){if(d.foam<.08&&d.dirt<.12){d.wet=Math.max(0,d.wet-dt*.48);changed=true}else toast('Primero enjuaga bien el panel')}else if(tool==='polish'){if(d.dirt<.08&&d.foam<.05&&d.wet<.08){d.shine=Math.min(1,d.shine+dt*(.3+up.polish*.09));changed=true}else toast('El panel debe estar limpio y seco')}if(changed){score+=Math.round(dt*70);updatePanelVisual(p);updateSpray(point);spray.visible=true}}
function updateSpray(end){const nozzle=player.getObjectByName('nozzle');const start=new THREE.Vector3();nozzle.getWorldPosition(start);const arr=spray.geometry.attributes.position.array;for(let i=0;i<sprayCount;i++){const t=Math.random();arr[i*3]=THREE.MathUtils.lerp(start.x,end.x,t)+(Math.random()-.5)*t*.45;arr[i*3+1]=THREE.MathUtils.lerp(start.y,end.y,t)+(Math.random()-.5)*t*.35;arr[i*3+2]=THREE.MathUtils.lerp(start.z,end.z,t)+(Math.random()-.5)*t*.45}spray.geometry.attributes.position.needsUpdate=true;spray.material.color.set(tool==='foam'?0xffffff:tool==='polish'?lime:0xaeefff)}
function targetPanel(){const rect=canvas.getBoundingClientRect();const x=mobileAim?0:((pointer.x-rect.left)/rect.width)*2-1,y=mobileAim?0:-((pointer.y-rect.top)/rect.height)*2+1;raycaster.setFromCamera({x,y},camera);return raycaster.intersectObjects(washable,false)[0]}
function complete(){if(gameState!=='game')return;gameState='complete';using=false;spray.visible=false;const reward=missionMode==='detail'?900:450;saved.money+=reward;saved.rep+=1;saved.xp+=500;if(saved.xp>=5000){saved.level++;saved.xp-=5000}save();$('#rewardMoney').textContent='$'+reward;$('#missionComplete').classList.remove('hidden');$('#hud').classList.add('hidden');$('#crosshair').classList.add('hidden');$('#mobileControls').classList.add('hidden')}
function chaos(){if(gameState!=='game')return;wanted=Math.min(5,wanted+1);vehicleDamage=Math.min(100,vehicleDamage+22);saved.money+=80;saved.rep=Math.max(0,saved.rep-50);washable[Math.floor(Math.random()*washable.length)].userData.damage=Math.min(1,vehicleDamage/100);washable.forEach(updatePanelVisual);score=Math.max(0,score-100);toast('Mala decisión: búsqueda activada',true);updateHUD()}
function updateHUD(){const a=averages(),p=Math.round(progressValue());$('#money').textContent=saved.money.toLocaleString();$('#rep').textContent=saved.rep.toLocaleString();$('#level').textContent=saved.level;$('#score').textContent=score.toLocaleString();$('#objectiveBar').style.width=p+'%';$('#progressText').textContent=p+'%';$('#dirtStat').textContent=Math.round(a.dirt*100)+'%';$('#foamStat').textContent=Math.round(a.foam*100)+'%';$('#wetStat').textContent=Math.round(a.wet*100)+'%';$('#shineStat').textContent=Math.round(a.shine*100)+'%';$('#stars').textContent='★'.repeat(wanted)+'☆'.repeat(5-wanted);const m=Math.floor(timeLeft/60),s=Math.max(0,Math.floor(timeLeft%60));$('#timer').textContent=missionMode==='free'?'LIBRE':String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');$('#upgradeMoney').textContent=saved.money.toLocaleString();const dist=player.position.distanceTo(car.position);$('#actionMessage').textContent=dist<6?'Apunta a una zona y mantén para usar '+tool.toUpperCase():'Acércate al vehículo para trabajar.'}
function showUpgrades(){$('#upgradeScreen').classList.remove('hidden');$('#upgradeMoney').textContent=saved.money.toLocaleString()}
function pause(){if(gameState==='game'){gameState='paused';$('#pauseScreen').classList.remove('hidden')}else if(gameState==='paused'){gameState='game';$('#pauseScreen').classList.add('hidden')}}
function frame(){requestAnimationFrame(frame);const now=performance.now(),dt=Math.min((now-last)/1000,.045);last=now;if(gameState==='game'){const mx=(keys.d||moveTouch.right?1:0)-(keys.a||moveTouch.left?1:0),mz=(keys.s||moveTouch.down?1:0)-(keys.w||moveTouch.up?1:0);const v=new THREE.Vector3(mx,0,mz);if(v.lengthSq()>0){v.normalize();player.position.addScaledVector(v,4.2*dt);player.position.x=THREE.MathUtils.clamp(player.position.x,-10,10);player.position.z=THREE.MathUtils.clamp(player.position.z,-7,10);player.rotation.y=Math.atan2(v.x,v.z);player.position.y=Math.abs(Math.sin(now*.008))*.035}else player.position.y=0;const desired=new THREE.Vector3(player.position.x+8,5.7,player.position.z+10);camera.position.lerp(desired,1-Math.pow(.0015,dt));camera.lookAt(player.position.x,1.35,player.position.z-1);spray.visible=false;if(using&&player.position.distanceTo(car.position)<6){const hit=targetPanel();if(hit)applyTool(hit.object,dt,hit.point)}if(missionMode!=='free'){timeLeft-=dt;if(timeLeft<=0){timeLeft=0;toast('Tiempo agotado. Reiniciando misión.',true);resetMission(missionMode)}const a=averages();if(a.dirt<.035&&a.foam<.035&&a.wet<.035&&a.shine>.72)complete()}updateHUD()}renderer.render(scene,camera)}

addEventListener('keydown',e=>{if(e.code==='KeyW'||e.code==='ArrowUp')keys.w=true;if(e.code==='KeyS'||e.code==='ArrowDown')keys.s=true;if(e.code==='KeyA'||e.code==='ArrowLeft')keys.a=true;if(e.code==='KeyD'||e.code==='ArrowRight')keys.d=true;if(e.code==='Digit1')setTool('foam');if(e.code==='Digit2')setTool('rinse');if(e.code==='Digit3')setTool('dry');if(e.code==='Digit4')setTool('polish');if(e.code==='KeyB')chaos();if(e.code==='Escape')pause();if(e.code==='Enter'&&gameState==='menu')start('wash')});
addEventListener('keyup',e=>{if(e.code==='KeyW'||e.code==='ArrowUp')keys.w=false;if(e.code==='KeyS'||e.code==='ArrowDown')keys.s=false;if(e.code==='KeyA'||e.code==='ArrowLeft')keys.a=false;if(e.code==='KeyD'||e.code==='ArrowRight')keys.d=false});
canvas.addEventListener('pointermove',e=>{pointer.x=e.clientX;pointer.y=e.clientY});canvas.addEventListener('pointerdown',e=>{if(gameState==='game'&&e.button===0)using=true});addEventListener('pointerup',()=>using=false);canvas.addEventListener('contextmenu',e=>e.preventDefault());
$$('.tool[data-tool]').forEach(b=>b.addEventListener('click',()=>setTool(b.dataset.tool)));$('#chaosBtn').addEventListener('click',chaos);$('#startBtn').addEventListener('click',()=>start('wash'));$('#washBtn').addEventListener('click',()=>start('wash'));$('#detailBtn').addEventListener('click',()=>start('detail'));$('#freeBtn').addEventListener('click',()=>start('free'));$('#upgradeBtn').addEventListener('click',showUpgrades);$('#closeUpgrades').addEventListener('click',()=>$('#upgradeScreen').classList.add('hidden'));$('#backMenu').addEventListener('click',goMenu);$('#nextMission').addEventListener('click',()=>{$('#missionComplete').classList.add('hidden');$('#hud').classList.remove('hidden');$('#crosshair').classList.remove('hidden');$('#mobileControls').classList.remove('hidden');gameState='game';resetMission(Math.random()>.45?'detail':'wash')});$('#resumeBtn').addEventListener('click',pause);$('#pauseMenuBtn').addEventListener('click',goMenu);
$$('.buy').forEach(b=>b.addEventListener('click',()=>{const price=+b.dataset.price,u=b.dataset.upgrade;if(saved.money<price)return toast('Fondos insuficientes',true);if(saved.upgrades[u]>=5)return toast('Mejora al máximo');saved.money-=price;saved.upgrades[u]++;save();$('#upgradeMoney').textContent=saved.money.toLocaleString();b.textContent='Nivel '+saved.upgrades[u]+' adquirido';toast('Mejora instalada')}));
$$('[data-move]').forEach(b=>{const k=b.dataset.move;b.addEventListener('pointerdown',e=>{e.preventDefault();moveTouch[k]=true});['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,e=>{e.preventDefault();moveTouch[k]=false}))});$('#mobileAction').addEventListener('pointerdown',e=>{e.preventDefault();mobileAim=true;using=true});['pointerup','pointercancel','pointerleave'].forEach(ev=>$('#mobileAction').addEventListener(ev,e=>{e.preventDefault();using=false;mobileAim=false}));
$('#loading').classList.add('hidden');frame();